version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "development"
    labels:
      - "mvn dependencies"

  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
    target-branch: "development"
    labels:
      - "npm dependencies"