FROM maven:3.6.3-openjdk-11 AS build

ARG build
ARG version

WORKDIR /tmp

# Copy code and compile
COPY . .

RUN echo "version: $version\nbuild: $build" > consumer/src/main/resources/build.yml

WORKDIR /tmp
RUN mvn install

FROM tomcat:jdk15-openjdk-oracle
COPY --from=build /tmp/consumer/target/link-consumer.war /usr/local/tomcat/webapps/ROOT.war
EXPOSE 8080
CMD ["catalina.sh", "run"]
