FROM maven:3.6.3-openjdk-11 AS build

WORKDIR /tmp

# Copy code and compile
COPY . .

WORKDIR /tmp
RUN mvn install

FROM tomcat:jdk15-openjdk-oracle
COPY --from=build /tmp/query-api/target/link-query-api.war /usr/local/tomcat/webapps/ROOT.war
EXPOSE 8080
CMD ["catalina.sh", "run"]
