### STAGE 1: Build ###
FROM node:12.7-alpine AS build
WORKDIR /usr/src/app
COPY ./web/package.json ./
COPY ./web/package-lock.json ./
RUN apk add python alpine-sdk
RUN npm ci
RUN npm install -g @angular/cli
COPY web/ .
RUN ng build --prod

### STAGE 2: Run ###
FROM nginx:1.17.1-alpine
COPY web/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /usr/src/app/dist /usr/share/nginx/html
