FROM maven:3.6.3-openjdk-11 AS build

RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring

ARG build
ARG version

WORKDIR /tmp

# Copy code and compile
COPY . .

RUN echo "version: $version\nbuild: $build" > datastore/src/main/resources/build.yml

WORKDIR /tmp
RUN mvn install -DskipTests

FROM tomcat:jdk15-openjdk-oracle
COPY --from=build /tmp/datastore/target/link-datastore.war /usr/local/tomcat/webapps/ROOT.war
EXPOSE 8080
CMD ["catalina.sh", "run"]
