### STAGE 1: Build ###
FROM node:14.15-alpine AS build

RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring

WORKDIR /usr/src/app
COPY ./web/package.json ./
COPY ./web/package-lock.json ./
RUN apk add python alpine-sdk=alpine=3.0
RUN npm ci
RUN npm install -g @angular/cli
COPY web/ .
RUN ng build --prod

### STAGE 2: Run ###
FROM nginx:1.21-alpine
COPY web/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /usr/src/app/dist /usr/share/nginx/html
