FROM tomcat:9.0.65-jre17-temurin-jammy
RUN apt-get update && apt-get install -y netcat
RUN useradd -U -d ${CATALINA_HOME} -s /bin/bash tomcat && chown -R tomcat:tomcat ${CATALINA_HOME}
USER tomcat:tomcat
COPY consumer/target/link-consumer.war /usr/local/tomcat/webapps/ROOT.war
EXPOSE 8080
CMD ["catalina.sh", "run"]

