FROM maven:3.6.3-openjdk-11 AS build

ARG build
ARG version

WORKDIR /tmp

# Copy code and compile
COPY . .

RUN echo "version: $version\nbuild: $build" > query-api/src/main/resources/build.yml

WORKDIR /tmp
RUN mvn install -pl query-api -am

FROM tomcat:jdk15-openjdk-oracle
COPY --from=build /tmp/query-api/target/link-query-api.war /usr/local/tomcat/webapps/agent.war
EXPOSE 8080
CMD ["catalina.sh", "run"]
