# Wipes a Single Postgres Database.

trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

variables:
  db: $(DATABASE)
  db_user: $(DATABASE_USER)
  db_pass: $(DATABASE_PASS)
  ns: $(NAMESPACE)
  deploy_fhir: $(DEPLOYMENT_FHIR)

steps:
- task: Kubernetes@1
  displayName: Scale Down FHIR Server
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'NHSNLink - Pay-As-You-Go(71125262-e1d6-4961-9803-8cb376d00871)'
    azureResourceGroup: 'nhsnlink-rg'
    kubernetesCluster: 'nhsnlink-aks'
    command: 'scale'
    arguments: 'deployment $(deploy_fhir) --replicas=0 -n $(ns)'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'

- task: AzureCLI@2
  displayName: Drop Database
  inputs:
    azureSubscription: 'postgres-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'

    inlineScript: |
      export PGPASSWORD=$(db_pass)
      psql --host=nhsnlink-db.postgres.database.azure.com --username=$(db_user) --no-password --dbname=$(db) --set=sslmode=require << EOF
      DROP SCHEMA public CASCADE;
      CREATE SCHEMA public;
      GRANT ALL ON SCHEMA public TO it;
      GRANT ALL ON SCHEMA public TO public;
      COMMENT ON SCHEMA public IS 'standard public schema created by script';
      EOF

- task: Kubernetes@1
  displayName: Scale up FHIR server
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'NHSNLink - Pay-As-You-Go(71125262-e1d6-4961-9803-8cb376d00871)'
    azureResourceGroup: 'nhsnlink-rg'
    kubernetesCluster: 'nhsnlink-aks'
    command: 'scale'
    arguments: 'deployment $(deploy_fhir) --replicas=1 -n $(ns)'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
